---
Name: realtime_statistics
After:
  - 'mysite/*'
---
Injector:
  StatisticAdapter:
    class: Ntb\Statistics\BlackholeAdapter
    properties:
      host: localhost
      port: 2003

StatisticTask:
  Separator: .
  Namespace: ntb